In [100]:
import pandas as pd
import numpy as np
import matplotlib as mpl
from numpy.linalg import inv
from numpy import array
from sklearn.model_selection import train_test_split

In [101]:
a = pd.read_csv('input.csv')
print(a.shape)

(323, 10)


In [102]:
print(data.head)
      

<bound method NDFrame.head of      Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0         665.1      271.13    8.200000  102.224650   31.899410      2617.0   
1          80.4      610.00   12.276712   80.263380   41.167540      1108.0   
2         150.0      322.58   24.200000  105.728950   38.851920      1673.0   
3          74.2       37.40    1.000000   80.105800   32.501110      4280.0   
4        2127.8     1613.20   17.291781  117.034431   30.512646        13.0   
5         672.1     1884.48   15.350685  114.350052   36.096851        71.0   
6         708.0     2326.00   11.412329  122.984383   41.115257        49.0   
7        2000.0     3358.00   22.000000  113.543870   22.198740        40.0   
8         188.0      887.43    3.700000  107.387650   40.743210      1042.0   
9        1198.9      501.34   16.900000  106.754760   31.849014       443.0   
10        910.0     1253.10   16.013699  117.361381   32.939243        25.0   
11        262.9     37

In [103]:
a_inverse = np.linalg.pinv(data)
print(a_inverse.shape)
print(a_inverse)

(10, 323)
[[ 6.29969521e-07  8.44127567e-06 -1.12151700e-05 ... -1.30218946e-05
  -2.28176933e-06 -3.35950071e-06]
 [-5.53363428e-07 -4.80054149e-07 -7.06700952e-07 ...  3.48632568e-06
  -7.71241215e-07  1.41598208e-06]
 [-1.00802094e-03  5.35489791e-03  7.48078597e-03 ...  6.49787734e-04
   1.87808358e-03  6.52420371e-05]
 ...
 [-3.38551685e-04  1.24539891e-02  7.58719842e-03 ... -5.47860400e-03
  -4.05492925e-03 -5.93050486e-03]
 [ 5.11995762e-05 -2.26419245e-05 -7.45638379e-04 ... -1.16580217e-04
   2.43163062e-04  6.07281263e-04]
 [ 2.95583394e-05 -2.92902566e-05  6.74054256e-06 ... -1.02600200e-04
   2.21452881e-05 -4.42100968e-05]]


In [95]:
c = pd.read_csv('ans.txt')
print(c.shape)
print(c)

(323, 1)
     ans
0     23
1    137
2     85
3     28
4     79
5    110
6    111
7     44
8     53
9     58
10    96
11    45
12   111
13   220
14    56
15    23
16   296
17    63
18   142
19    59
20   105
21    31
22    69
23    51
24   116
25    22
26   224
27   106
28    49
29   118
..   ...
293   48
294  119
295  148
296   29
297   73
298   64
299  103
300  103
301   38
302   59
303  106
304   76
305   91
306  117
307   27
308   34
309   82
310  152
311   45
312   66
313   25
314   88
315   41
316   52
317  104
318   79
319   86
320  116
321  118
322   60

[323 rows x 1 columns]


In [104]:
b = np.dot(a_inverse, c)
print(b.shape)
print(b)

(10, 1)
[[-1.55470021e-02]
 [ 1.35342326e-03]
 [ 3.58584246e+00]
 [-1.13873207e+00]
 [ 5.47656592e+00]
 [-1.32795670e-02]
 [-2.06547180e-04]
 [-6.95168618e+00]
 [-1.80330260e-01]
 [ 2.28414315e-02]]


In [99]:
finalC = np.dot(a , b)
print(finalC.shape)
print(finalC)

(323, 1)
[[ 37.00184953]
 [155.99514628]
 [149.07662052]
 [ 26.45501087]
 [ 56.66854177]
 [107.40106554]
 [111.44380453]
 [ 25.99831889]
 [ 91.53551693]
 [ 82.3592604 ]
 [ 84.58999258]
 [110.55452678]
 [ 95.98025358]
 [118.11384002]
 [ 43.69919789]
 [ 45.18246732]
 [168.32781121]
 [ 97.18235126]
 [107.8290299 ]
 [ 71.7009268 ]
 [108.26957854]
 [ 34.51247008]
 [ 68.80074234]
 [ 68.20038172]
 [ 76.47416033]
 [ 71.57564716]
 [124.82144186]
 [ 49.42366546]
 [ 53.93899417]
 [107.28866065]
 [111.60165837]
 [ 59.74869682]
 [108.1725012 ]
 [ 74.60522952]
 [ 30.64311598]
 [ 91.70943075]
 [ 25.00479353]
 [111.59413745]
 [122.49293083]
 [ 96.13284219]
 [ 86.66128678]
 [ 41.85783084]
 [ 93.81628193]
 [114.37347194]
 [ 23.1273857 ]
 [ 59.14268204]
 [104.58830203]
 [ 90.54675859]
 [ 74.37843035]
 [ 65.18327064]
 [102.4262788 ]
 [ 55.15143398]
 [ 51.20379268]
 [ 97.98127546]
 [ 57.38498547]
 [110.36054005]
 [ 94.13339241]
 [ 47.10754028]
 [ 43.00287632]
 [ 56.77658535]
 [ 40.13980049]
 [ 84.54434117]

[[-1.55470021e-02]
 [ 1.35342326e-03]
 [ 3.58584246e+00]
 [-1.13873207e+00]
 [ 5.47656592e+00]
 [-1.32795670e-02]
 [-2.06547180e-04]
 [-6.95168618e+00]
 [-1.80330260e-01]
 [ 2.28414315e-02]]


(323, 1)
